name: Test and Build plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: npm ci

    - name: Test
      run: npm test

    - name: Build
      run: |
        npm run build
        zip -r Emmet.zip ./Emmet.novaextension

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Nova extension
        path: ./Emmet.zip
